version: '3.8'

services:
  discordbot:
    build: .
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - BASE_DIR=/data
    volumes:
      - ./data:/data
    command: python3 discordbot.py
